apiVersion: v1
kind: Service
metadata:
  name: nats-service

spec:
  type: NodePort
  ports:
    - targetPort: 4222
      port: 4222
      nodePort: 30009
  selector:
    app: nats-app
    name: nats-pod
        