apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: k8s-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-pod
      app: k8s-test-app
  template:
    metadata:
      name: mysql-pod
      labels:
        name: mysql-pod
        app: k8s-test-app

    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: 123456sdfwreS
        ports:
        - containerPort: 3306