apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    name: app-service
    app: k8s-test-app
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30008
  selector:
      name: app-pod
      app: k8s-test-app