apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    name: db-service
    app: k8s-test-app
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    name: mysql-pod
    app: k8s-test-app